storeflextech/uiservice

storeflex/package.json, storeflex/src/components/atoms/textfield/InputBox.tsx, storeflex/src/components/panels/profile/addProfile.tsx, storeflex/src/utils/CommonUtils.ts, storeflex/src/utils/HelperFunction.tsx, storeflex/yarn.lock
added input box on change and on blur code.
=> added input on change and on blur code

storeflex/package.json, storeflex/src/App.css, storeflex/src/App.tsx, storeflex/src/pages/dashboard.tsx, storeflex/src/pages/signin.tsx, storeflex/src/styles/sfglobal.scss, storeflex/src/utils/CommonUtils.ts, storeflex/yarn.lock
added utils functions in common files
=> added utils function for validation

storeflex/mock-server/server.js, storeflex/mock-server/signinData.json, storeflex/package.json, storeflex/src/App.css, storeflex/src/App.tsx, storeflex/src/api/Api.tsx, storeflex/src/api/ApiConfig.ts, storeflex/src/components/atoms/textfield/InputBox.tsx, storeflex/src/components/panels/profile/addProfile.tsx, storeflex/src/index.tsx, storeflex/src/pages/addbusiness.tsx, storeflex/src/pages/dashboard.tsx, storeflex/src/pages/signin.tsx, storeflex/src/styles/sfglobal.scss, storeflex/src/utils/CommonUtils.ts, storeflex/src/utils/Constants.ts, storeflex/src/utils/HelperFunction.tsx, storeflex/yarn.lock
=> Taking from master

storeflex/src/components/navbar/SideNavBar.tsx, storeflex/src/pages/PgDashboard.tsx, storeflex/src/pages/signin-new.tsx, storeflex/src/utils/CommonUtils.ts
Respective menu load based on login user type
=> Zaman storeflexui

storeflex/public/static/images/React App_files/bundle.js, storeflex/src/components/atoms/adduser/AddUser.tsx, storeflex/src/components/atoms/adduser/UserHelper.tsx, storeflex/src/components/panels/warehouseInfo/WearehouseAddress.tsx, storeflex/src/pages/ErrorPage.tsx
Profile photo and user role added
=> Profile Photo added

storeflex/src/components/atoms/addressforms/AddressDetails.tsx, storeflex/src/components/miscellaneous/contact.tsx, storeflex/src/components/panels/dashboards/UserDashboard.tsx, storeflex/src/pages/ErrorPage.tsx, storeflex/src/utils/MenuIItems.json
=> Nishanta storeflex

storeflex/src/components/miscellaneous/contact.tsx
formsubmit.co link removed.
Please verify and merge.
=> formsubmit.co removed.

storeflex/src/components/panels/warehouseInfo/AddWarehouse.tsx, storeflex/src/components/panels/warehouseInfo/WearehouseAddress.tsx, storeflex/src/components/panels/warehouseInfo/warehouseBeginningSection.tsx
Little changes in add warehouse page also we need more fields in warehouse post api as on ui
=> Little change

storeflex/src/api/Api.tsx, storeflex/src/api/ApiConfig.ts, storeflex/src/pages/viewuser.tsx
=> API integration in viewuser

storeflex/src/pages/viewuser.tsx
=> little changes

storeflex/src/pages/viewuser.tsx
=> Changes in buttons viewuser

storeflex/src/App.tsx, storeflex/src/components/atoms/payment/myorderstable.tsx, storeflex/src/pages/editCompanyUser.tsx, storeflex/src/pages/viewuser.tsx, storeflex/src/utils/Constants.ts
=> Created editCompanyUser

storeflex/src/components/panels/dashboards/ClientDashboard.tsx, storeflex/src/components/panels/warehouseInfo/WarehouseHours.tsx, storeflex/src/pages/viewuser.tsx, storeflex/src/utils/MenuIItems.json
=> Validation in Facility Hours

storeflex/src/components/atoms/profile/profile.tsx
=> redirection added in buttons in list space

storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/components/panels/warehouseInfo/WarehouseHours.tsx
=> bug fixes on SwalButton and radioButton

storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/components/atoms/profile/profileList.json
=> logout issue fixed

storeflex/src/components/panels/businessinfo/addBusiness.tsx
=> email attached in swal

storeflex/src/api/Api.tsx, storeflex/src/components/panels/warehouseInfo/ViewWarehouse.tsx
=> warehouse view

storeflex/src/components/navbar/SideNavList.json, storeflex/src/pages/editCompanyUser.tsx, storeflex/src/pages/userProfile.tsx
=> change password added

storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/pages/userProfile.tsx
=> change password button add

storeflex/src/components/atoms/adduser/AddUser.tsx, storeflex/src/components/panels/warehouseInfo/EditWarehouse.tsx, storeflex/src/pages/editCompanyUser.tsx
=> photo added

storeflex/src/components/panels/warehouseInfo/component/WarehouseLayout.tsx
=> dock high door validation added

storeflex/src/components/panels/warehouseInfo/component/WarehouseLayout.tsx
=> validation done in warehouseLayout

storeflex/src/components/panels/warehouseInfo/AddWarehouse.tsx
please verify the code and merge.
=> Validation Done in Addwarehouse

storeflex/src/components/panels/warehouseInfo/AddWarehouse.tsx
Please verify the code and merge
=> Remaining validations done in Addwarehouse

storeflex/src/components/atoms/Searchresult/warehouseDetails.tsx, storeflex/src/components/panels/warehouseInfo/EditWarehouse.tsx
=> Changes in WarehouseDetails and Validations added in EditWarehouse.

storeflex/src/components/atoms/Searchresult/searchresult.tsx, storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/components/panels/businessinfo/editBusiness.tsx, storeflex/src/components/panels/warehouseInfo/AddWarehouse.tsx, storeflex/src/components/panels/warehouseInfo/EditWarehouse.tsx, storeflex/src/components/panels/warehouseInfo/ViewWarehouse.tsx, storeflex/src/pages/cart.tsx, storeflex/src/pages/signup.tsx, storeflex/src/pages/viewuser.tsx
=> resolving conflicts

storeflex/src/pages/faq.tsx
=> Changes in FAQ

storeflex/src/components/footer/footer.tsx, storeflex/src/pages/userProfile.tsx, storeflex/src/utils/CommonUtils.ts
=> userProfile imported

storeflex/src/pages/addpayment.tsx
=> Tables done in Payment details.

storeflex/src/pages/paymentHistory.tsx
=> Changes in PaymentDetails

storeflex/src/utils/Constants.ts
=> page Loading issue is fixed in payment history

storeflex/src/components/atoms/payment/myorderstable.tsx, storeflex/src/pages/bookings.tsx
=> Tables done in Bookings and Order Details.

storeflex/src/App.tsx, storeflex/src/components/atoms/profile/profileList.json, storeflex/src/pages/ChangePass.tsx, storeflex/src/pages/ForgotPass.tsx, storeflex/src/pages/SigninPage.tsx
=> changePass improved

storeflex/src/App.tsx, storeflex/src/components/navbar/SideNavList.json, storeflex/src/pages/PaymentRecievable.tsx, storeflex/src/utils/Constants.ts
=> Changes and error fixed

storeflex/src/components/atoms/Searchresult/searchresult.tsx, storeflex/src/components/atoms/Searchresult/warehouseDetails.tsx, storeflex/src/components/atoms/profile/profileList.json, storeflex/src/pages/ChangePass.tsx, storeflex/src/pages/SigninPage.tsx
=> email ID disabled in ForgotPass

storeflex/src/App.tsx, storeflex/src/components/atoms/Searchresult/searchresult.tsx, storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/components/panels/contactus/ContactUs.tsx, storeflex/src/components/panels/warehouseInfo/component/WearehousePricing.tsx, storeflex/src/pages/ForgotPass.tsx, storeflex/src/pages/SigninPage.tsx, storeflex/src/pages/applogout.tsx, storeflex/src/pages/faq.tsx, storeflex/src/utils/CommonUtils.ts
=> Name and Email populated in ContactUS

storeflex/src/components/atoms/Searchresult/searchresult.tsx, storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/components/atoms/profile/profileList.json, storeflex/src/components/miscellaneous/prime-section.tsx, storeflex/src/components/panels/dashboards/UserDashboard.tsx
=> search issue fixed

storeflex/src/api/Api.tsx, storeflex/src/components/atoms/Searchresult/searchresult.tsx, storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/components/atoms/textfield/InputBox.tsx, storeflex/src/components/cart-contents/cart-contents.tsx, storeflex/src/components/miscellaneous/prime-section.tsx
=> timer and date added

storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/components/cart-contents/cart-contents.tsx, storeflex/src/pages/Steps.tsx, storeflex/src/pages/applogout.tsx
=> Step Indicator added

storeflex/src/components/atoms/Searchresult/searchresult.tsx, storeflex/src/components/atoms/payment/orderReview.tsx, storeflex/src/components/atoms/textfield/InputBox.tsx, storeflex/src/components/cart-contents/cart-contents.tsx, storeflex/src/components/panels/payment/paymentStatus.tsx
=> step indicator added, scrollToTop improved

storeflex/src/components/atoms/profile/profileList.json
=> remove wishlists

storeflex/src/pages/signup.tsx
=> SignUp issue solved

storeflex/src/components/atoms/profile/profile.tsx
=> search working in sidenav

storeflex/src/api/Api.tsx, storeflex/src/api/ApiConfig.ts, storeflex/src/pages/ChangePass.tsx
=> changepass api integration

storeflex/src/pages/paymentReport.tsx
=> Changes in paymentReport

storeflex/src/pages/ForgotChangePass.tsx
=> ForgotPassword improved

storeflex/src/App.tsx, storeflex/src/components/atoms/profile/profile.tsx, storeflex/src/components/navbar/SideNavList.json
=> roleBased page access

storeflex/src/components/panels/businessinfo/editBusiness.tsx, storeflex/src/components/panels/contactus/ContactUs.tsx
=> ContactUs bug fixed

storeflex/src/components/cart-contents/cart-contents.tsx, storeflex/src/components/panels/warehouseInfo/component/WearehousePricing.tsx
=> Date Validation added

storeflex/src/components/atoms/Searchresult/filter.tsx, storeflex/src/components/atoms/Searchresult/searchresult.tsx, storeflex/src/components/atoms/Searchresult/warehouseDetails.tsx, storeflex/src/components/panels/warehouseInfo/EditWarehouse.tsx, storeflex/src/components/panels/warehouseInfo/component/WearehousePricing.tsx, storeflex/src/components/user/viewUser.tsx, storeflex/src/pages/SigninPage.tsx, storeflex/src/utils/Constants.ts
=> Pricing added with two decimal

storeflex/src/App.tsx, storeflex/src/api/Api.tsx, storeflex/src/api/ApiConfig.ts, storeflex/src/cms/Content.json, storeflex/src/components/atoms/Searchresult/warehouseDetails.tsx, storeflex/src/components/panels/businessinfo/viewBusiness.tsx, storeflex/src/components/panels/dashboards/UserDashboard.tsx, storeflex/src/pages/FeaturedWH.tsx, storeflex/src/pages/cart.tsx, storeflex/src/utils/CommonUtils.ts, storeflex/src/utils/Constants.ts
=> view companies according to roleType

storeflex/src/components/atoms/company/GetCompany.tsx, storeflex/src/components/atoms/textfield/InputBox.tsx, storeflex/src/components/panels/warehouseInfo/component/WarehouseDetails.tsx
=> companyList alloted according to roleType

storeflex/src/api/Api.tsx, storeflex/src/api/ApiConfig.ts, storeflex/src/components/miscellaneous/pricing.tsx
=> featureWarehouse details added in HomePage
